//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TypingGameService.TypingGameWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TypingGameWebService.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name gradeLevel from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWordList", ReplyAction="*")]
        TypingGameService.TypingGameWebService.GetWordListResponse GetWordList(TypingGameService.TypingGameWebService.GetWordListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWordList", ReplyAction="*")]
        System.Threading.Tasks.Task<TypingGameService.TypingGameWebService.GetWordListResponse> GetWordListAsync(TypingGameService.TypingGameWebService.GetWordListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWordListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWordList", Namespace="http://tempuri.org/", Order=0)]
        public TypingGameService.TypingGameWebService.GetWordListRequestBody Body;
        
        public GetWordListRequest() {
        }
        
        public GetWordListRequest(TypingGameService.TypingGameWebService.GetWordListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWordListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string gradeLevel;
        
        public GetWordListRequestBody() {
        }
        
        public GetWordListRequestBody(string gradeLevel) {
            this.gradeLevel = gradeLevel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWordListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWordListResponse", Namespace="http://tempuri.org/", Order=0)]
        public TypingGameService.TypingGameWebService.GetWordListResponseBody Body;
        
        public GetWordListResponse() {
        }
        
        public GetWordListResponse(TypingGameService.TypingGameWebService.GetWordListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWordListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetWordListResult;
        
        public GetWordListResponseBody() {
        }
        
        public GetWordListResponseBody(string GetWordListResult) {
            this.GetWordListResult = GetWordListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : TypingGameService.TypingGameWebService.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<TypingGameService.TypingGameWebService.Service1Soap>, TypingGameService.TypingGameWebService.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TypingGameService.TypingGameWebService.GetWordListResponse TypingGameService.TypingGameWebService.Service1Soap.GetWordList(TypingGameService.TypingGameWebService.GetWordListRequest request) {
            return base.Channel.GetWordList(request);
        }
        
        public string GetWordList(string gradeLevel) {
            TypingGameService.TypingGameWebService.GetWordListRequest inValue = new TypingGameService.TypingGameWebService.GetWordListRequest();
            inValue.Body = new TypingGameService.TypingGameWebService.GetWordListRequestBody();
            inValue.Body.gradeLevel = gradeLevel;
            TypingGameService.TypingGameWebService.GetWordListResponse retVal = ((TypingGameService.TypingGameWebService.Service1Soap)(this)).GetWordList(inValue);
            return retVal.Body.GetWordListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TypingGameService.TypingGameWebService.GetWordListResponse> TypingGameService.TypingGameWebService.Service1Soap.GetWordListAsync(TypingGameService.TypingGameWebService.GetWordListRequest request) {
            return base.Channel.GetWordListAsync(request);
        }
        
        public System.Threading.Tasks.Task<TypingGameService.TypingGameWebService.GetWordListResponse> GetWordListAsync(string gradeLevel) {
            TypingGameService.TypingGameWebService.GetWordListRequest inValue = new TypingGameService.TypingGameWebService.GetWordListRequest();
            inValue.Body = new TypingGameService.TypingGameWebService.GetWordListRequestBody();
            inValue.Body.gradeLevel = gradeLevel;
            return ((TypingGameService.TypingGameWebService.Service1Soap)(this)).GetWordListAsync(inValue);
        }
    }
}
